# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Feature Branch

on:
  push:
    branches: [ feature/* ]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.8
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8
      - name: Run the Maven package phase
        run: mvn -B clean package -DskipTests
      - name: Run the Maven verify phase
        run: mvn -B clean verify
